apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: serviceinstances.osb.servicefabrik.io
spec:
  group: osb.servicefabrik.io
  names:
    kind: ServiceInstance
    plural: serviceinstances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            context:
              type: object
            organizationGuid:
              type: string
            parameters:
              type: object
            planId:
              type: string
            serviceId:
              type: string
            spaceGuid:
              type: string
          required:
          - serviceId
          - planId
          type: object
        status:
          properties:
            dashboardUrl:
              type: string
            error:
              type: string
            lastOperation:
              type: string
            response:
              type: string
            state:
              type: string
          required:
          - state
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
